
CREATE TABLE <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> ( "ID" INTEGER, "flowerType" varchar(4999), "scienceName" varchar(4999), "classification" varchar(4999), "description" varchar(4999), "wikiLink" varchar(4999));

INSERT INTO <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> VALUES (0, 'Daisy', 'Bellis Perennis', 'Angiosperms - Asteraceae', '"Daisy" is an herbaceous perennial plant with short creeping rhizomes and rosettes of small rounded or spoon-shaped leaves that are from 3/4 to 2 inches (approx. 2–5 cm) long and grow flat to the ground. The species habitually colonises lawns, and is difficult to eradicate by mowing - hence the term "lawn daisy". Wherever it appears it is often considered an invasive weed. The flowerheads are composite, in the form of a pseudanthium, consisting of many sessile flowers about 3/4 to 1-1/4 in (approx. 2–3 cm) in diameter, with white ray florets (often tipped red) and yellow disc florets. Each inflorescence is borne on single leafless stems 3/4 - 4 in (approx. 2–10 cm), rarely 6 in (approx. 15 cm) tall. The capitulum, or disc of florets, is surrounded by two rows of green bracts known as "phyllaries".', 'https://en.wikipedia.org/wiki/Bellis_perennis');

INSERT INTO <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> VALUES (1, 'Dandelion', 'Taraxacum', 'Angiosperms - Asteraceae ', 'Taraxacum is a large genus of flowering plants in the family Asteraceae which consists of species commonly known as "Dandelion". They are native to Eurasia and North America, but the two commonplace species worldwide, T. officinale and T. erythrospermum, were imports from Europe that now propagate as wildflowers.[2] Both species are edible in their entirety. The common name dandelion is given to members of the genus. Like other members of the Asteraceae family, they have very small flowers collected together into a composite flower head. Each single flower in a head is called a floret. Many Taraxacum species produce seeds asexually by apomixis, where the seeds are produced without pollination, resulting in offspring that are genetically identical to the parent plant.', 'https://en.wikipedia.org/wiki/Taraxacum');

INSERT INTO <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> VALUES (2, 'Rose', 'Rosa', 'Angiosperms - Rosaceae', '"Rose" is a woody perennial flowering plant of the genus Rosa, in the family Rosaceae, or the flower it bears. There are over a hundred species and thousands of cultivars. They form a group of plants that can be erect shrubs, climbing or trailing with stems that are often armed with sharp prickles. Flowers vary in size and shape and are usually large and showy, in colours ranging from white through yellows and reds. Most species are native to Asia, with smaller numbers native to Europe, North America, and northwestern Africa. Species, cultivars and hybrids are all widely grown for their beauty and often are fragrant. Roses have acquired cultural significance in many societies. Rose plants range in size from compact, miniature roses, to climbers that can reach seven meters in height. Different species hybridize easily, and this has been used in the development of the wide range of garden roses.', 'https://en.wikipedia.org/wiki/Rose');

INSERT INTO <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> VALUES (3, 'Sunflower', 'Helianthus', 'Angiosperms - Helianthus', 'Helianthus or sunflowers is a genus of plants comprising about 70 species in the family Asteraceae. The genus is one of many in the Asteraceae that are known as sunflowers. Except for three species in South America, all Helianthus species are native to North America. The common name, "sunflower", typically refers to the popular annual species Helianthus annuus, or the common sunflower, whose round flower heads in combination with the ligules look like the sun. This and other species, notably Jerusalem artichoke (H. tuberosus), are cultivated in temperate regions as food crops for cattle and poultry and ornamental plants. The largest sunflower field is located in Tuscany, Italy.', 'https://en.wikipedia.org/wiki/Helianthus');

INSERT INTO <YOUR_FLOWER_SCHEMA_NAME>.<YOUR_FLOWER_DETAILS_TABLE_NAME> VALUES (4, 'Tulip', 'Tulipa', 'Angiosperms - Liliaceae', 'The tulip is a Eurasian and North African genus of herbaceous, perennial, bulbous plants in the lily family, with showy flowers. About 75 wild species are currently accepted. The genus native range extends west to the Iberian Peninsula, through North Africa to Greece, the Balkans, Turkey, throughout the Levant (Syria, Israel, Palestinian Territories, Lebanon, Jordan) and Iran, north to Ukraine, southern Siberia and Mongolia, and east to the Northwest of China.The tulips centre of diversity is in the Pamir, Hindu Kush, and Tien Shan mountains.It is a common element of steppe and winter-rain Mediterranean vegetation. A number of species and many hybrid cultivars are grown in gardens or as potted plants.', 'https://en.wikipedia.org/wiki/Tulip');
